version: '3.5'

services:
  places:
    build: .
    image: photoprism/places:develop
    depends_on:
      - places-db
    ports:
      - "8080:8080" # HTTP
    volumes:
      - ".:/go/src/github.com/photoprism/photoprism-places"
    environment:
      PLACES_DEBUG: "true"
      PLACES_EXPERIMENTAL: "true"
      PLACES_DATABASE_DSN: "places:places@tcp(places-db:3306)/places?parseTime=true"
      PLACES_DATABASE_DRIVER: "mysql"
      PLACES_SERVER_MODE: "debug"
      PLACES_ASSETS_PATH: "/go/src/github.com/photoprism/photoprism-places/assets"
      PLACES_CACHE_PATH: "/go/src/github.com/photoprism/photoprism-places/assets/cache"
      PLACES_CONFIG_PATH: "/go/src/github.com/photoprism/photoprism-places/assets/config"

  places-db:
    image: mariadb:10.4.11
    command: mysqld --port=3306 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=1024
    expose:
      - "3306"
    ports:
      - "3306:3306" # MariaDB
    environment:
      MYSQL_ROOT_PASSWORD: places
      MYSQL_USER: places
      MYSQL_PASSWORD: places
      MYSQL_DATABASE: places
